-- sql/04_build_business_views.sql
-- Vistas y tablas de negocio (GOLD layer)
-- Responden directamente a las 8 preguntas de negocio de la prueba técnica

USE DATABASE ${DB};
USE SCHEMA ${SCHEMA_GOLD};

-- PREGUNTA 1: Órdenes, Ventas y Ganancia por Año
CREATE OR REPLACE VIEW V_ORDERS_SALES_PROFIT_BY_YEAR AS
SELECT
    ORDER_YEAR AS YEAR,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT,
    ROUND(AVG(SALES), 2) AS AVG_ORDER_VALUE,
    -- Crecimiento YoY (útil para análisis de tendencias)
    ROUND((SUM(SALES) - LAG(SUM(SALES)) OVER (ORDER BY ORDER_YEAR)) 
        / LAG(SUM(SALES)) OVER (ORDER BY ORDER_YEAR) * 100, 2) AS SALES_GROWTH_PCT,
    ROUND((SUM(PROFIT) - LAG(SUM(PROFIT)) OVER (ORDER BY ORDER_YEAR))
        / LAG(SUM(PROFIT)) OVER (ORDER BY ORDER_YEAR) * 100, 2) AS PROFIT_GROWTH_PCT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
GROUP BY ORDER_YEAR
ORDER BY YEAR DESC;

-- PREGUNTA 2: Órdenes por Día de la Semana (2017)
CREATE OR REPLACE VIEW V_ORDERS_BY_DAY_OF_WEEK_2017 AS
SELECT
    DAY_OF_WEEK,
    DAY_NAME,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(AVG(SALES), 2) AS AVG_SALES,
    ROUND(AVG(PROFIT), 2) AS AVG_PROFIT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
WHERE ORDER_YEAR = 2017
GROUP BY DAY_OF_WEEK, DAY_NAME
ORDER BY DAY_OF_WEEK;

-- PREGUNTA 3: Ventas por Segmento (Todos los años)
CREATE OR REPLACE VIEW V_SALES_BY_SEGMENT_ALL_YEARS AS
SELECT
    ORDER_YEAR AS YEAR,
    SEGMENT,
    COUNT(DISTINCT ORDER_ID) AS SEGMENT_ORDERS,
    ROUND(SUM(SALES), 2) AS SEGMENT_SALES,
    ROUND(SUM(PROFIT), 2) AS SEGMENT_PROFIT,
    ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS SEGMENT_PROFIT_MARGIN_PCT,
    ROUND(SUM(SALES) / SUM(SUM(SALES)) OVER (PARTITION BY ORDER_YEAR) * 100, 2) AS SEGMENT_SALES_MIX_PCT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
GROUP BY ORDER_YEAR, SEGMENT
ORDER BY YEAR, SEGMENT_SALES DESC;

-- PREGUNTA 4: Top 10 Productos por Ventas (2017)
CREATE OR REPLACE VIEW V_TOP_10_PRODUCTS_2017 AS
SELECT
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS QUANTITY_SOLD,
    ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
WHERE ORDER_YEAR = 2017
GROUP BY PRODUCT_ID, PRODUCT_NAME, CATEGORY, SUB_CATEGORY
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- PREGUNTA 5: Bottom 10 Productos por Ventas (2015)
CREATE OR REPLACE VIEW V_BOTTOM_10_PRODUCTS_2015 AS
SELECT
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS QUANTITY_SOLD,
    ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
WHERE ORDER_YEAR = 2015
GROUP BY PRODUCT_ID, PRODUCT_NAME, CATEGORY, SUB_CATEGORY
ORDER BY TOTAL_SALES ASC
LIMIT 10;

-- PREGUNTA 6: Órdenes Devueltas en 2015
CREATE OR REPLACE VIEW V_RETURNED_ORDERS_2015 AS
SELECT
    COUNT(DISTINCT ORDER_ID) AS RETURNED_ORDERS,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES_RETURNED,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT_RETURNED
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
WHERE ORDER_YEAR = 2015 AND IS_RETURNED = 1;

-- PREGUNTA 7: Órdenes Devueltas por Gerente Regional (2015)
CREATE OR REPLACE VIEW V_RETURNED_BY_MANAGER_2015 AS
SELECT
    p.REGIONAL_MANAGER,
    o.REGION,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS_REGION,
    COUNT(DISTINCT CASE WHEN o.IS_RETURNED = 1 THEN o.ORDER_ID END) AS RETURNED_ORDERS_REGION,
    ROUND(COUNT(DISTINCT CASE WHEN o.IS_RETURNED = 1 THEN o.ORDER_ID END) * 100.0 
        / COUNT(DISTINCT o.ORDER_ID), 2) AS RETURN_RATE_PCT,
    ROUND(SUM(o.SALES), 2) AS TOTAL_SALES_REGION,
    ROUND(SUM(o.PROFIT), 2) AS TOTAL_PROFIT_REGION,
    ROUND(AVG(o.PROFIT), 2) AS AVG_PROFIT_PER_ORDER
FROM ${SCHEMA_SILVER}.CURATED_ORDERS o
LEFT JOIN ${SCHEMA_SILVER}.CURATED_PEOPLE p ON o.REGION = p.REGION
WHERE o.ORDER_YEAR = 2015
GROUP BY p.REGIONAL_MANAGER, o.REGION
ORDER BY RETURNED_ORDERS_REGION DESC;

-- PREGUNTA 8: KPIs de Desempeño de la Empresa
CREATE OR REPLACE VIEW V_COMPANY_PERFORMANCE_KPI AS
WITH yearly_data AS (
    SELECT
        ORDER_YEAR,
        COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
        ROUND(SUM(SALES), 2) AS TOTAL_SALES,
        ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
        ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT,
        ROUND(AVG(SALES), 2) AS AVG_ORDER_VALUE,
        ROUND(SUM(CASE WHEN PROFIT < 0 THEN 1 ELSE 0 END) * 100.0 
            / COUNT(DISTINCT ORDER_ID), 2) AS NEGATIVE_PROFIT_ORDER_PCT,
        ROUND(SUM(CASE WHEN IS_RETURNED = 1 THEN 1 ELSE 0 END) * 100.0 
            / COUNT(*), 2) AS RETURN_RATE_PCT
    FROM ${SCHEMA_SILVER}.CURATED_ORDERS
    GROUP BY ORDER_YEAR
)
SELECT
    ORDER_YEAR AS YEAR,
    TOTAL_ORDERS,
    UNIQUE_CUSTOMERS,
    TOTAL_SALES,
    TOTAL_PROFIT,
    PROFIT_MARGIN_PCT,
    AVG_ORDER_VALUE,
    NEGATIVE_PROFIT_ORDER_PCT,
    RETURN_RATE_PCT,
    ROUND((TOTAL_SALES - LAG(TOTAL_SALES) OVER (ORDER BY ORDER_YEAR))
        / LAG(TOTAL_SALES) OVER (ORDER BY ORDER_YEAR) * 100, 2) AS SALES_GROWTH_PCT,
    ROUND((TOTAL_PROFIT - LAG(TOTAL_PROFIT) OVER (ORDER BY ORDER_YEAR))
        / LAG(TOTAL_PROFIT) OVER (ORDER BY ORDER_YEAR) * 100, 2) AS PROFIT_GROWTH_PCT
FROM yearly_data
ORDER BY YEAR DESC;

-- ANÁLISIS CRÍTICO: Rentabilidad de Productos
-- Esto responde al hallazgo: 37,71% de productos con margen negativo

CREATE OR REPLACE VIEW V_PRODUCT_PROFITABILITY_ANALYSIS AS
WITH product_metrics AS (
    SELECT
        ORDER_YEAR,
        CATEGORY,
        SUB_CATEGORY,
        PRODUCT_NAME,
        COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
        ROUND(SUM(SALES), 2) AS TOTAL_SALES,
        ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
        ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT,
        CASE WHEN SUM(PROFIT) < 0 THEN 1 ELSE 0 END AS IS_LOSS_MAKING
    FROM ${SCHEMA_SILVER}.CURATED_ORDERS
    GROUP BY ORDER_YEAR, CATEGORY, SUB_CATEGORY, PRODUCT_NAME, PRODUCT_ID
)
SELECT
    ORDER_YEAR AS YEAR,
    CATEGORY,
    COUNT(DISTINCT CASE WHEN IS_LOSS_MAKING = 1 THEN PRODUCT_NAME END) AS LOSS_MAKING_PRODUCTS,
    COUNT(DISTINCT PRODUCT_NAME) AS TOTAL_PRODUCTS,
    ROUND(COUNT(DISTINCT CASE WHEN IS_LOSS_MAKING = 1 THEN PRODUCT_NAME END) * 100.0
        / COUNT(DISTINCT PRODUCT_NAME), 2) AS PCT_LOSS_MAKING,
    ROUND(SUM(CASE WHEN IS_LOSS_MAKING = 1 THEN TOTAL_PROFIT ELSE 0 END), 2) AS TOTAL_LOSSES,
    ROUND(SUM(TOTAL_SALES), 2) AS TOTAL_CATEGORY_SALES
FROM product_metrics
GROUP BY ORDER_YEAR, CATEGORY
ORDER BY YEAR, PCT_LOSS_MAKING DESC;

-- ANÁLISIS CRÍTICO: Órdenes no Rentables
-- Esto responde al hallazgo: 49,93% de órdenes no rentables

CREATE OR REPLACE VIEW V_UNPROFITABLE_ORDERS_ANALYSIS AS
SELECT
    ORDER_YEAR AS YEAR,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT CASE WHEN PROFIT < 0 THEN ORDER_ID END) AS LOSS_ORDERS,
    ROUND(COUNT(DISTINCT CASE WHEN PROFIT < 0 THEN ORDER_ID END) * 100.0
        / COUNT(DISTINCT ORDER_ID), 2) AS PCT_LOSS_ORDERS,
    ROUND(SUM(CASE WHEN PROFIT < 0 THEN PROFIT ELSE 0 END), 2) AS TOTAL_LOSSES,
    ROUND(SUM(CASE WHEN PROFIT < 0 THEN SALES ELSE 0 END), 2) AS LOSS_ORDER_SALES,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
GROUP BY ORDER_YEAR
ORDER BY YEAR DESC;

-- ANÁLISIS: Desempeño Regional
CREATE OR REPLACE VIEW V_REGIONAL_PERFORMANCE AS
SELECT
    ORDER_YEAR AS YEAR,
    REGION,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
    ROUND(SUM(PROFIT) / SUM(SALES) * 100, 2) AS PROFIT_MARGIN_PCT,
    ROUND(SUM(CASE WHEN IS_RETURNED = 1 THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2) AS RETURN_RATE_PCT
FROM ${SCHEMA_SILVER}.CURATED_ORDERS
GROUP BY ORDER_YEAR, REGION
ORDER BY YEAR, TOTAL_SALES DESC;

-- RESUMEN DE VISTAS CREADAS
SELECT 
    table_name,
    'VIEW' AS object_type
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = '${SCHEMA_GOLD}'
ORDER BY table_name;